language: android

sudo: required

before_install:
  - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-24

script:
  - ./gradlew test
